# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate config file

on:
  push:
    branches:
      - 'main'
    paths:
      - 'meme/*'
      - '.github/workflows/generate-config-file.yml'

jobs:
  generate-config-file:
    name: Generate config file
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
      - name: build config
        run: |
          ./shell/computed.sh
          cat static/scripts/config.js
      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: update config file'
          file_pattern: static/scripts/config.js
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
